name: 'Publish Electron App'

on:
  push:
    tags:
      - 'v*.*.*' # vで始まるタグ（例: v1.0.2）がPushされたときに実行

jobs:
  publish-app:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # このステップを新たに追加
      - name: Install build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg rpm

      - name: Install dependencies
        run: npm ci

      - name: Publish application
        run: npm run publish
        env:
          # リポジトリのSecretsに設定したトークンを使用
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}