name: 'Publish Electron App (Windows)'

# このワークフローが実行されるタイミングを定義
on:
  push:
    tags:
      - 'v*.*.*' # vで始まるタグ（例: v1.0.2）がPushされたときに実行

jobs:
  publish-windows:
    runs-on: windows-latest

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Node.js環境をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # 3. 依存関係をインストール
      - name: Install dependencies
        run: npm ci

      # 4. アプリケーションをビルド
      - name: Build application
        run: npm run make

      # 5. exeインストーラーを作成
      - name: Build exe installer
        run: npm run build

      # 6. アーティファクトをアップロード
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: |
            dist/MyApp Setup *.exe
            out/make/zip/win32/x64/*.zip 