name: 'Publish Windows App'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-windows:
    runs-on: windows-latest

    # This block grants the necessary permissions to the job
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and Publish Windows application
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}